App:
  Name: streamer_system                      # API Server的名字
  InstantKey: streamer_system_1             # 同一个服务在同一个Environment下可能部署了多套时，就用该字段区分
  Addr: :9000                              # HTTP绑定端口
  RunMode: test                           # 开发模式, dev, release, test
  UseSwagger: true                       # 是否开启swagger, true，false
  JwtSecret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
  JwtExpire: 604800        # 小时
Log:
  Writers: file,stdout            # 有2个可选项：file,stdout, 可以两者同时选择输出位置，有2个可选项：file,stdout。选择file会将日志记录到logger_file指定的日志文件中，选择stdout会将日志输出到标准输出，当然也可以两者同时选择
  LoggerLevel: DEBUG             # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  LoggerFile: log/logic.log   # 日志文件
  LogFormatText: false          # 日志的输出格式，json或者plaintext，true会输出成plaintext格式，false会输出成json格式
  LogRollingPolicy: size      # rotate依据，可选的有：daily,size
  LogRotateDate: 1              # rotate转存时间，配合rollingPolicy: daily使用
  LogRotateSize: 1              # rotate转存大小，配合rollingPolicy: size使用，单位：Mb
  LogBackupCount: 7             # 当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。

Mysql:
  Default:
    Name: aov_streamer_admin_system
    Addr: 127.0.0.1:3306 # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
    Username: root
    Password: root
    ShowLog: true                  # 是否打印SQL日志
    MaxIdleConn: 200               # 最大闲置的连接数
    MaxOpenConn: 900               # 最大打开的连接数
    ConnMaxLifeTime: 60          # 连接重用的最大时间，单位分钟
  Material:
    Name: aov_streamer_admin_material    # db name
    Addr: 127.0.0.1:3306           # db 地址
    Username: root                 # 用户名
    Password: root                 # 密码
    ShowLog: true                  # 是否打印SQL日志
    MaxIdleConn: 200               # 最大闲置的连接数
    MaxOpenConn: 900               # 最大打开的连接数
    ConnMaxLifeTime: 60          # 连接重用的最大时间，单位分钟
Redis:
  Default:
    Addr: "127.0.0.1:6379"
    Password: "" # no password set
    Db: 0 # use default DB
    DialTimeout: 5s
    ReadTimeout: 3s
    WriteTimeout: 3s
    PoolSize: 15000
    PoolTimeOut: 4s
#  GCP配置
GCP:
  CDN: https://creatorhub-storage.intlgame.com/
  KeyName: creatorhub11
  Key: 0PFhNJeQNN3b8-IXGrK1uQ==

EmailAPI: # 发送邮箱API配置
  Domain: test.intlgame.com
  Uri: /v2/transmit/email
  GameId: 11
  Sigkey: sigkey
  ChannelId: 1
  Source: 0
OAuth:
  Youtube: # youtube账号绑定的配置
    AuthUrl: https://accounts.google.com/o/oauth2/auth  # oauth认证网关
    TokenUrl: https://oauth2.googleapis.com/token       # 用code 换取access token的网关
    RedirectUri: https://aov-test.creatorhuub.com/api/v1/userInfo/youtube/oauth/redirect   # 后端重定向uri
    ClientId: 277828511900-m7va6rtf66o3d1rccim2po4gevd7p4jl.apps.googleusercontent.com  # client id
    ClientSecret: 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                                              # client secret
    LoginRedirectUri: https://aov-test.creatorhuub.com/home/signmiddle
    YoutubeMinFans: 0 #youtube MIN FANS
ContentModeration: #内容审核
  Domain: dev.intlgame.com
  Uri: /v1/sec/contentmoderation/uic
  Appkey: nZBGqgH8hsGLhcQZVeEj1wYK
  Appid: fc53Cq1HgZbnNI09W0nIHQsxiOZKGc0O
  Gameid: 7
  BusiheadAppkey: key1
  BusiheadServicename: service1
Docusign:
  Env: demo
  # The public key of the docusign
  PublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkJDs/oaKMlaL/9ifFxMC
    I+ASltItrvLP5giknoct2eyCKRl1lubm8xShY6hVClerGDHeAei88iq+xS80GvQM
    UzMt2GIXsFkJXlPjQpUwwU7vjE3c6JO45n4PHatMgF24y8BYhhygz/r0LXUS/spR
    fBfjw+xrAHM9sBM+5rphJk/qNlHezLjRSeUJtLg3gsVOcHt4SBmx95ot9Un/mnCf
    97HdYQaQ36OLAb1avENekieLGjQsOotjqzOBOi81S5hQHX6TFCUWy5afLtBh1cuf
    B+ADHO6amUQacYZtiC3qKt3G68mfLzHj4i5FqZbPks39srGxaeB9qhSQX/u6KfWs
    8wIDAQAB
    -----END PUBLIC KEY-----
  # The private key of the docusign
  PrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAkJDs/oaKMlaL/9ifFxMCI+ASltItrvLP5giknoct2eyCKRl1
    lubm8xShY6hVClerGDHeAei88iq+xS80GvQMUzMt2GIXsFkJXlPjQpUwwU7vjE3c
    6JO45n4PHatMgF24y8BYhhygz/r0LXUS/spRfBfjw+xrAHM9sBM+5rphJk/qNlHe
    zLjRSeUJtLg3gsVOcHt4SBmx95ot9Un/mnCf97HdYQaQ36OLAb1avENekieLGjQs
    OotjqzOBOi81S5hQHX6TFCUWy5afLtBh1cufB+ADHO6amUQacYZtiC3qKt3G68mf
    LzHj4i5FqZbPks39srGxaeB9qhSQX/u6KfWs8wIDAQABAoIBAAGqA7PPmGzw6ldo
    62cj52xIoYjQ3xTZEYDG7fqRF1z0w46FCQGbhOJZr8E+bOJ3JB85Dvf1qEyriAKB
    Z6t0C2W0Wv7pixu9yLw6gBMv7FF9uMRYAQPGjjZ+KqgLg3HngMKeVwmT/EMmWQb6
    vXpnUG0NAH4URyrCU4Ks6XfbLVY1MM8VwZS5GTvDAyUPpd2+pHr0dEP9Jebmzbxu
    xVmbrCti+Fv9A1mfNG3fxSDvF2GVag4BcCWsmpFQLxFzzxqkmVQIIdfpjcjM8skE
    GEoZqVUkaKm2kubcwtOi9pLBzm+lw50NGcBlGEfouS2UbM7vWTkCeKeCbZRfZaEH
    G4eX1FkCgYEAy8az62Z/3vJz4TYhLB2K4mj+VLbZCrx9+Pj5loItLM41CvFyJxW5
    Akc1ZJDZDdiMDlPUx0+q8HnEmE980gGwtrUB0IpH8mgkBsTFuUHRZhK6NHfmEfcN
    VFGe8Q+cY/TDArdt5LIupRsgGMs9kTLx+Mkj3aX8h2mkUHk/GnN7UksCgYEAtZ2V
    ZyM4/FOogJv07dpKJCD2KxGBCSNTtQGi2udbxaJPXSjMP8kx0ZI4JqqcBMpvCQvu
    iTJmh06WdYC+PM5XEwJeDTPaB4eAFVPrj9AMnC0fHmvEHArJ5QXvaesYpTx52tEy
    wmyIuV3ygXBullwOrD9G0z8dpNAiAcE9f0cypvkCgYEAoUvoMGWSw8OAC/0Ppt6/
    h1V6M04EYKYwxHk2/naOEZArljzlkaB1MCNzVOX+mSIWQmUC4Lzj3rNT9Qe+EnD6
    ErUV+Z7rMipSkfUBWRGLEVOzhkJ9nyzBpUNyHvevX8Nm9OiCmOqdV10wO8/sLNl5
    hOaZeCGh0QHC6Vv/og1UyR8CgYBekdYQRKkRy0Y84fjiOf7NXVSSDKVSatDVuiph
    LoP9H42QBwSEWnHUnP0cNU7Ut8ylu07Upif5YRS7zvRAmXmB7oOnAE8SCJ7LfE13
    L3DBikVgA+G0cHG9DiAi2UaWFC2nobN6xiVT0PXMLQ2Iwhrp2nE44u6+uZpbq5Io
    Spy3kQKBgHTPaPMlzZfcvYzi6cyb7Ur5UoSRzEvDw6c55iSnty2T1ovMx5+OyBbR
    wPnY5jK2GIJC0bOB6AufH5YGItj3Ch5oZOhshZJW5blhugpDY9caggB73xPZGHAg
    J5Fu4a9iNWMXPZGkwLSAgp/hAQ8kSlYdOyAAM6kf4coeXf9WYIJZ
    -----END RSA PRIVATE KEY-----
  ClientId: a3272141-68da-4304-a921-6397dd492261
  RedirectUri: https://pubgmobile.creatorhuub.com/home/docusignmiddle
  WebhookUri: https://pubgmobile.creatorhuub.com/api/v1/user/docusign/notifyEnvelopeStatus
  Sub: f385711f-9bb5-4cfe-818e-21a8f2c02b03
  TemplateId:
    cn: 82cbb661-f9e0-4c38-a3a0-48318c7c116f    #cn简体中文
    cnh: 6c061fae-084a-4657-9ee8-7325c3c4b3d2   #cnh繁体中文（香港）
    cnt: 6c061fae-084a-4657-9ee8-7325c3c4b3d2   #cnt繁体中文（台湾）
    yu: 3947ccb5-ef30-42ed-bf73-e2e14af7cfb1    #yu越南语
    tu: 7ab63672-d3e7-4b0b-a4d8-257fa551676e    #tu土耳其语
    ta: 04100835-29f6-4237-bffa-be065ad1aaa1    #ta泰语
    py: 1a91fa82-bdf1-4afc-b8dc-a352354461e4    #py俄语
    po: 5b3ca281-adeb-4f64-9a77-8a5a3a42a1c2    #po葡萄牙语（葡萄牙）
    ma: 5e239998-0106-4353-95ff-a09157df642c    #ma马来语（马来西亚）
    in: 0e3425da-e2c8-4dd7-90a7-93956632e49a    #in印尼语
    fr: e46faa6b-5670-4ec7-9b65-0181329fa964    #fr法语
    es: 5d33852d-ad35-4620-845c-dc619e0aaa16    #es西班牙语（西班牙）
    en: ae421f70-4731-4619-943c-99e8437f80ee    #en英语
    de: 6f6d4395-01c0-4825-bef6-270101ce7fcf    #de德语
    ar: 53a8f754-7f58-4830-89ca-92a99105cb85    #ar阿拉伯语
    #us 美国区域|sg 新加坡区域|ru 俄罗斯区域|eu 欧洲区域
  ClientRegion: sg
  ConnectKey: lVk6ShQ5d6n57WQXRoj9e0QAqcnzsMQBwj+e4j3ozLU=
WhiteList: [ "jingshenwei93@gmail.com","382533537@qq.com","sarahkim@krafton.com","787482984@qq.com","2834964850@qq.com" ]
